### ISSUE TITLE
UI类应该怎么组织进来，有没有例子

### ISSUE THREAD

**Issue by chenny2024** [CreatorMC/MODSDKSping#1]
``[21:45:13] Traceback (most recent call last):
[21:45:13]   File "mod/common/minecraftMod.py", line 848, in ImportModMain
[21:45:13]   File "TechWeaponScripts.modMain", line 27, in TechWeaponModClientInit
[21:45:13]   File "mod/client/extraClientApi.py", line 43, in RegisterSystem
[21:45:13]   File "mod/common/baseApp.py", line 175, in RegisterSystem
[21:45:13]   File "mod/common/system/baseSystemManager.py", line 42, in RegisterSystem
[21:45:13]   File "TechWeaponScripts.plugins.MODSDKSpring.core.ListenEvent", line 91, in newInit
[21:45:13]   File "TechWeaponScripts.plugins.MODSDKSpring.core.BeanFactory", line 98, in createBean
[21:45:13]   File "TechWeaponScripts.plugins.MODSDKSpring.core.BeanFactory", line 196, in createBeanDfs
[21:45:13]   File "TechWeaponScripts.plugins.MODSDKSpring.core.ListenEvent", line 137, in newInit
[21:45:13] TypeError: __init__() takes exactly 4 arguments (2 given)

上面是报错，下面是代码

================
```java
import time
import mod.client.extraClientApi as clientApi
from ..modCommon.modConfig import *
from ..plugins.MODSDKSpring.core.ListenEvent import ListenEvent

ViewBinder = clientApi.GetViewBinderCls()
ViewRequest = clientApi.GetViewViewRequestCls()
ScreenNode = clientApi.GetScreenNodeCls()

Namespace = clientApi.GetEngineNamespace()
SystemName = clientApi.GetEngineSystemName()
CompFactory = clientApi.GetEngineCompFactory()
gameComp = CompFactory.CreateGame(clientApi.GetLevelId())

@ListenEvent.InitComponentClient()
class GunUI(ScreenNode):
    def __init__(self, namespace, name, param):
        ScreenNode.__init__(self, namespace, name, param)
        self.mPlayerId = clientApi.GetLocalPlayerId()
        self.mClientSystem = clientApi.GetSystem(MOD_NAMESPACE, CLIENT_SYSTEM_NAME)
        self.mItemComp = CompFactory.CreateItem(self.mPlayerId)
        self.mQueryVariableComp = CompFactory.CreateQueryVariable(self.mPlayerId)
```

**Comment by CreatorMC** [comment]
UI 类不应该成为“组件”，正常创建 UI 类即可（就像没有 MODSDKSpring 那样），然后，如果想以“组件”的方式管理 UI，您可以再新建一个“客户端组件”，在这个组件内创建 UI。

下方是示例：
UI 类：
```python
# -*- coding: utf-8 -*-
import time
import mod.client.extraClientApi as clientApi
ViewBinder = clientApi.GetViewBinderCls()
ViewRequest = clientApi.GetViewViewRequestCls()
ScreenNode = clientApi.GetScreenNodeCls()
compFactory = clientApi.GetEngineCompFactory()
levelId = clientApi.GetLevelId()
playerId = clientApi.GetLocalPlayerId()

class TMSTickUI(ScreenNode):
    def __init__(self, namespace, name, param):
        ScreenNode.__init__(self, namespace, name, param)

    def Create(self):
        pass

    def Destroy(self):
        pass

```

创建 UI 的客户端组件：
```python
from ironHammerModScripts.plugins.MODSDKSpring.core.ListenEvent import ListenEvent
from ironHammerModScripts.modCommon import modConfig
import mod.client.extraClientApi as clientApi
compFactory = clientApi.GetEngineCompFactory()
levelId = clientApi.GetLevelId()
playerId = clientApi.GetLocalPlayerId()

@ListenEvent.InitComponentClient
class TickUIClientComponent(object):

    def __init__(self, client):
        self.client = client
        # 保存 UI 对象
        self.tickUIScreenNode = None

    @ListenEvent.Client(eventName="UiInitFinished")
    def uiInitFinished(self, event):
        """
        UI初始化框架完成,此时可以创建UI
        """
        clientApi.RegisterUI(modConfig.MOD_NAMESPACE, "tms_tick_ui", "ironHammerModScripts.ui.TMSTickUI.TMSTickUI", "tms_tick_ui.main")
        self.tickUIScreenNode = clientApi.CreateUI(modConfig.MOD_NAMESPACE, "tms_tick_ui", {"isHud": 1})
```

其他组件可以通过 TickUIClientComponent 调用 UI 对象。

**Comment by chenny2024** [comment]
了解了 非常感谢
